version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: plannr
      POSTGRES_PASSWORD: plannr
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    command: redis-server --requirepass plannr
    ports:
      - "6379:6379"